name: terraform

on:
  pull_request:
    paths:
      - '**.tf'
      - '.github/workflows/terraform.yml'
  push:
    branches: [main]

permissions:
  contents: read
  pull-requests: write

jobs:
  fmt-validate:
    name: fmt + validate (${{ matrix.env }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env: [dev, staging, prod]
    steps:
      - uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5
      - name: terraform fmt
        run: terraform fmt -check -recursive
      - name: terraform init (no backend)
        run: terraform -chdir=envs/${{ matrix.env }} init -backend=false
      - name: terraform validate
        run: terraform -chdir=envs/${{ matrix.env }} validate

  tflint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: terraform-linters/setup-tflint@v4
      - run: tflint --init
      - run: tflint --recursive

  tfsec:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: aquasecurity/tfsec-action@v1.0.3
        with:
          soft_fail: false

  checkov:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: terraform
          quiet: true
          soft_fail: false
